version: '3.8'

services:
  client_ui:
    build: .
    image: angular-client:latest
    container_name: client_ui
    ports:
      - "8081:80"
    networks:
      - api_gateway

networks:
  api_gateway:
    driver: bridge