# docker run -d -p 5000:5000 --restart=always --name registry registry:2
# docker tag node-api-products:1.0 localhost:5000/node-api-products:1.0
# docker push localhost:5000/node-api-products:1.0
# docker pull localhost:5000/node-api-products:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
      - name: node-api-products
        image: localhost:5000/node-api-products:1.0
        ports:
        - containerPort: 3301
        env:
        - name: PORT
          value: "3301"
        - name: NODE_ENV
          value: "prod"
        - name: DB_URL
          value: "http://admin:Fallas2024@host.docker.internal:5984"
        - name: DB_COOKIE
          value: "645CEDB9CB2AAAFE698923D0C9BAAC37"
        - name: DB_NAME
          value: "amazoops"