apiVersion: v1
kind: Service
metadata:
  name: products-microservice
spec:
  selector:
    app: products-microservice
  ports:
    - protocol: TCP
      port: 13301
      targetPort: 3301
  type: LoadBalancer