version: '3.8'

services:
  orders_microservice:
    image: node-api-orders:latest
    container_name: orders_microservice
    env_file: ./.env.production.local
    networks:
      - api_gateway
    ports:
      - "3302:3302"

networks:
  api_gateway:
    driver: bridge